### ISSUE TITLE
bug: error: target is not supported, for more information see: https://docs.rs/getrandom/#unsupported-targets

### ISSUE THREAD

**Issue by l-monninger** [movementlabsxyz/movement#1]
# Summary
`getrandom` cannot target RISC0 `zkVM`.

## Steps to Reproduce
In `zkfp` dir, run `cargo check`.

**Comment by Hoangtu12** [comment]
> # Summary
> `getrandom` cannot target RISC0 `zkVM`.
> 
> ## Steps to Reproduce
> In `zkfp` dir, run `cargo check`.
