### ISSUE TITLE
Suggestions about movement engine.

### ISSUE THREAD

**Issue by jamesatomc** [movementlabsxyz/movement#138]
Can you make an engine movement sdk that can create its own chains? After all, the Cosmos side developed the engine to create chains.  And it's a good result from the ecosystem that I observed and tried to play with move ment sdk. The movement sdk has standards for writing move sui and aptos. I think we should do it quickly.  I will see many developers interested in building something that uses moveVM and evm because it creates new use cases and is very beneficial to developers who want to build their own chains.

**Comment by l-monninger** [comment]
Thanks, @jamesatomc! This is the vision. Would you mind moving this over to Discussion (#50).

**Comment by jamesatomc** [comment]
Can you make an engine movement sdk that can create its own chains? After all, the Cosmos side developed the engine to create chains. And it's a good result from the ecosystem that I observed and tried to play with move ment sdk. The movement sdk has standards for writing move sui and aptos. I think we should do it quickly. I will see many developers interested in building something that uses moveVM and evm because it creates new use cases and is very beneficial to developers who want to build their own chains.
