### ISSUE TITLE
Deployment: update suzuka-devnet to e6cb8e287cb837af6e61451f2ff405047dd285c9

### ISSUE THREAD

**Issue by radupopa369** [movementlabsxyz/movement#176]
Deployment: update suzuka-devnet to e6cb8e287cb837af6e61451f2ff405047dd285c9

This is a ticket for deployment to `e6cb8e287cb837af6e61451f2ff405047dd285c9`

**Comment by andyjsbell** [comment]
@radupopa369 can this be closed?

**Comment by radupopa369** [comment]
yes now
