### ISSUE TITLE
Explorer 404 when linking to any page except root

### ISSUE THREAD

**Issue by Rahat-ch** [movementlabsxyz/movement#177]
**Describe the bug**
We can look up transactions and accounts via the searchbar and on suzuka explorer but when sharing the links they 404 

example:

https://explorer.testnet.suzuka.movementlabs.xyz/account/0xd1126ce48bd65fb72190dbd9a6eaa65ba973f1e1664ac0cfba4db1d071fd0c36

If I look up the above account directly in browser I can look up the account however when I share the link and open it the page will 404

**To Reproduce**

- Search any account or transaction this works
- share the url page to anyone or try to to open url in new tab
- see 404 page

**Expected behavior**
sharing the url to the page should result in the expected information to be shown

**Comment by andyjsbell** [comment]
Looks like this one got fixed @Rahat-ch can you confirm please?

**Comment by Rahat-ch** [comment]
Yes this is fixed closing issue
