### ISSUE TITLE
Remove ad-hoc JSON formatting in sequencer blobs

### ISSUE THREAD

**Issue by mzabaluev** [movementlabsxyz/movement#182]
In #171, sequence numbers are introduced in a little kludgy way, by imposing JSON encoding on a `bytes` field of a protobuf message. Move these values to be first-class fields of the protobuf message instead.

_Originally posted by @mzabaluev in https://github.com/movementlabsxyz/movement/pull/171#discussion_r1672390762_

**Comment by andyjsbell** [comment]
@mzabaluev can this be closed?

**Comment by mzabaluev** [comment]
@andyjsbell this is resolved by #253, which is not merged yet.

**Comment by mzabaluev** [comment]
Done in #299.
