### ISSUE TITLE
Subject: Urgent: Issue with Token Swapping and Move to Razor in M1 Devnet & M2 Devnet

### ISSUE THREAD

**Issue by Mdmohdirfan111** [movementlabsxyz/movement#193]
Dear Tech Team,

I hope this message finds you well. I am writing to bring to your attention an issue I've encountered while attempting to swap tokens on both M1 Devnet and M2 Devnet environments.

Specifically, I am experiencing the following problems:

Token Swapping Error: When attempting to swap tokens, I am encountering an error where the process hangs indefinitely at "Fetching best price...". This delay significantly impacts usability.
![Uploading ss.jpg…]()

Move to Razor Failure: Additionally, during the token swapping process, I intermittently encounter failures when attempting to proceed with "Move to Razor".

These issues are occurring consistently across both development networks and are impacting my workflow significantly.

Could you please investigate and resolve these issues at your earliest convenience? If further information or access to logs is needed, please let me know, and I will provide them promptly.

Thank you for your prompt attention to this matter.

Best regards,

Mohd Irfan
0x044ea1c74ae0b4a3e4f498bcf8820ddee645bd6f42542ef203ffa2c942ba37cd

**Comment by andygolay** [comment]
Hi, I would raise this with Razor wallet, thanks.
