### ISSUE TITLE
Implement Connection Manager for bridge clients

### ISSUE THREAD

**Issue by 0xmovses** [movementlabsxyz/movement#250]
Bridge clients need to be `Clone`. See the comment here https://github.com/movementlabsxyz/movement/pull/153#discussion_r1684345723

We need a nicely designed connection manager because of this https://github.com/movementlabsxyz/movement/pull/153#issuecomment-2247596412

**Comment by andygolay** [comment]
Closing as this was solved and the fix implemented a few days ago.
