### ISSUE TITLE
Layout flipping upside down

### ISSUE THREAD

**Issue by profxmew** [movementlabsxyz/movement#264]
**Describe the bug**
Switching networks while on transaction history tab makes the layout flip and gives no response.

**To Reproduce**
1. On Testnet go to 'Transaction/Activity history'
2. Switch network to M1
3. See Error

**Expected behavior**
Network switch without layout flipping.

**Screenshots**
![Screenshot 2024-07-28 032500](https://github.com/user-attachments/assets/c9ea4d87-69cb-4dfd-a58e-2dd4a533b3bb)

**Desktop**
 - OS: Windows
 - Browser: Edge
 - Version: 126.0

**Additional context**
Restart the wallet to get back as normal

**Comment by radupopa369** [comment]
Hey [profxmew](https://github.com/profxmew)  can you please clarify on which UI component you are reporting this bug?
Please paste in the link you are using/

**Comment by profxmew** [comment]
> Hey [profxmew](https://github.com/profxmew) can you please clarify on which UI component you are reporting this bug? Please paste in the link you are using/

 bottom 3rd UI component
