### ISSUE TITLE
Antivirus software detects a virus

### ISSUE THREAD

**Issue by P300777** [movementlabsxyz/movement#267]
**Describe the bug**

**To Reproduce**
1. Go to 'https://www.brkt.gg/'
2. Click on '連結錢包'
3. See error

**Screenshots**
![1722258894594](https://github.com/user-attachments/assets/6d7bb42c-bc26-4e0b-a771-7b3c4b8d2a5c)

**Comment by mzabaluev** [comment]
I don't think we can do anything about blocking heuristics in third-party antivirus software, without further information on what may be causing the block.
