### ISSUE TITLE
nightly wallet and razor wallet displaying different balances on the same chain.

### ISSUE THREAD

**Issue by MesomaMadu** [movementlabsxyz/movement#279]
**Describe the bug**
When a new wallet is created on nightly and is being imported on razor wallet, the faucet i requested appears to be showing different balances after requesting from nightly and razor wallets, making it difficult to complete testnet tasks.

**To Reproduce**
1. Go to 'razor wallet'
2. Click on 'settings'
3. Scroll down to 'import wallet'
4. import wallet to nightly wallet and request faucet to see the errors.

**Expected behavior**
Different balances after requesting from faucet.

**Screenshots**
![Screenshot 2024-07-31 152649](https://github.com/user-attachments/assets/40e62956-d37e-4eb9-bab9-6505b6deee38)
![Screenshot 2024-07-31 152710](https://github.com/user-attachments/assets/6270413f-57b8-4bb2-b357-e8274c651023)

**Desktop (please complete the following information):**
 - OS: [windows 11]
 - Browser [chrome]

**Smartphone (please complete the following information):**
 - Device: [Xaomi redmi note 13]
 - OS: [Android(hyperOS 1.0.4.0)]
 - Browser [chrome]
 - Version [14]

**Additional context**
And then again, the galxe website has been refusing to authorize the movement website from accessing the required information needed to login.

**Comment by l-monninger** [comment]
It could be that they are in fact pointing to different networks that we have. Are you still experiencing this issue?
