### ISSUE TITLE
Routex testnet explorer error

### ISSUE THREAD

**Issue by cryptopunkstar** [movementlabsxyz/movement#280]
**Describe the bug**
Unknown error fetching transaction with version or hash 0xaa74cb3bfd7f1a00afe4d41fd1d8678e43c3db0821a961c9cdd71e319fa3aedb:
AxiosError: Network Error
Try again later

Solution
On Routex the explorer parameter is configuration on mainnet. 
Change a parameter in testnet !

**To Reproduce**
1. Go to '[...](https://routex.io/trade/swap)'
2. Click on 'SWAP'
3. Click to 'windows box explorer'

**Expected behavior**
Show explorer in testnet.

**Screenshots**
![xroute](https://github.com/user-attachments/assets/be680838-c31e-4521-9657-09dbe85f458b)

**Desktop (please complete the following information):**
 - OS: [Ubuntu]
 - Browser [chrome]
 - Version [Version 127.0.6533.72 (Build officiel) (64 bits)]

**Additional context**
Good link eplorer
https://blue.explorer.movementlabs.xyz/txn/0x448dab452d5fcdf8efb0ba01b9d68d68fbccf1305e0c3f3484aec79701ea8508?network=testnet
Bad link explorer result error
https://blue.explorer.movementlabs.xyz/txn/0x448dab452d5fcdf8efb0ba01b9d68d68fbccf1305e0c3f3484aec79701ea8508?network=mainnet

See you, Cryptopunkstar

**Comment by l-monninger** [comment]
I believe @0xPrimata took care of this a while back.
