### ISSUE TITLE
Bug pending transactions in the aptos movement network

### ISSUE THREAD

**Issue by jalu017** [movementlabsxyz/movement#282]
![Annotation 2024-08-01 043534](https://github.com/user-attachments/assets/67f5b751-c596-47d6-b1fa-87ba6630f5c7)
![Annotation 2024-08-01 043652jh](https://github.com/user-attachments/assets/89a224c8-072f-45c4-8ca0-ae01aea5c7bf)
I did a testnet on razordex using the aptos movement network, then the transaction was delayed so I couldn't make any transactions using the movement testnet network,

**Comment by l-monninger** [comment]
Probably load related.
