### ISSUE TITLE
Stream <> Movement - Web App tasks

### ISSUE THREAD

**Issue by D413422** [movementlabsxyz/movement#285]
**Describe the bug**
In the Stream protocol, the cryptocurrency is not displaying, and I cannot add it to vaults.

**To Reproduce**
1. Go to 'https://app.streamprotocol.money'
2. Click on 'USDC'
3. And you will see that you can't add token

**Screenshots**
https://ibb.co/nD9nrps   https://ibb.co/cvX4CSZ

**Desktop (please complete the following information):**
 - OS: [e.g Windows 11]
 - Browser [e.g. chrome,Opera]
 - Version [e.g. 110]

**Comment by bhenhsi** [comment]
Please reach out to the Stream protocol team. This repo is for Movement network protocol development.
