### ISSUE TITLE
faucet not show to nightl wallet

### ISSUE THREAD

**Issue by Tandojt** [movementlabsxyz/movement#289]
![Screenshot 2024-08-02 004606](https://github.com/user-attachments/assets/99ed8dd9-6449-40d6-924c-42b27aff2f5b)
**Describe the bug*
for niglty wallet to claim faucet to mevm network

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bhenhsi** [comment]
Please reach out to Nightly team.
