### ISSUE TITLE
No Study. Battle. Build. role granted

### ISSUE THREAD

**Issue by tomikaz9** [movementlabsxyz/movement#291]
**Describe the bug**
I had completed the Galxe task and claimed, but not yet received the Study. Battle. Build. role. Please help me check. My galxe ID: ManishK14986132, EVM address:0x151C64022f96db3E11a5d951719d69a15a383866, My Discord: warpathhouse1.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by andygolay** [comment]
Hi, Movement Discord could be a good place to ask about this. This repo is related to engineering rather than specific community programs.
