### ISSUE TITLE
Repeated Token Approval on StableJack

### ISSUE THREAD

**Issue by Tunchie522** [movementlabsxyz/movement#292]
When depositing moveUSD on stableJack token approval is requested at every time a user wants to deposit 

**To Reproduce**
1. Go to Earn
2. Click on Deposit moveUSD
3. Input amount and approve allowance
4. On the next deposit and approval is required over again

**Expected behavior**

**Screenshots**
After the first approval, it's is expected that subsequent deposits shouldn't require approval over again

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Brave
 - Version 1.47.186

**Comment by andygolay** [comment]
Hi for issues with StableJack please reach out to StableJack support, thanks.
