### ISSUE TITLE
error while doing swap in razor dex

### ISSUE THREAD

**Issue by dimscm** [movementlabsxyz/movement#301]
![Screenshot 2024-08-04 113810](https://github.com/user-attachments/assets/7c64a07f-e322-4f8e-8eae-ac5486938c49)

**Comment by Cryptokhad** [comment]
Can I confirm to team that these types of errors are useful helpful to upload but should be moved to the Ecosystem repostoriies?

**Comment by andygolay** [comment]
Hi, for issues in Razor DEX, please reach out to Razor team, thanks.
