### ISSUE TITLE
PAR-1 Use a Higher Security Level Hash Function 

### ISSUE THREAD

**Issue by SA124** [movementlabsxyz/movement#323]
Severity: Informational
Status: Pending
Auditor: Movebit
Topic:Suzuka-only custom components

PAR-1 Use a Higher Security Level Hash Function
Severity: Informational
Discovery Methods:
Status: Pending
Code Location:
networks/suzuka/suzuka-full-node/src/partial.rs#199-202
Descriptions:
It is recommended to use a higher security level hash function (eg.sha3)The Sha256
algorithm is susceptible to hash length expansion attacks and will require urgent upgrades in
the future if security issues arise

<img width="971" alt="Screenshot 2024-08-08 at 12 41 21 PM" src="https://github.com/user-attachments/assets/6a60204e-fb6f-447f-b683-ab8e162fda8f">

Suggestion:
It is recommended to use a higher security level hash function (eg.sha3)

**Comment by l-monninger** [comment]
We have changed to `blake3` since this was reviewed.
