### ISSUE TITLE
ROC-2 Incorrect Implementation of get_rightmost_leaf Leading to Inaccurate Node Retrieval

### ISSUE THREAD

**Issue by SA124** [movementlabsxyz/movement#325]
ROC-2 Incorrect Implementation of get_rightmost_leaf
Leading to Inaccurate Node Retrieval

Severity: Minor
Discovery Methods: Manual Review
Status: Pending
Auditor: Movebit
Topic: Suzuka-only custom components

Code Location:
protocol-units/storage/jelly-move/src/rocksdb.rs#156-164

Descriptions:
The function get_rightmost_leaf might not return the actual rightmost leaf node.
The issue arises because using rocksdb::IteratorMode::End results in keys being sorted in
descending order based on their serialized byte representation using borsh::to_vec(). This
means higher versions of `NodeKeNodeKey will be sorted before lower versions, even if the
latter is actually the rightmost leaf. For example:
NodeKey { version: 1, nibble_path: e } will be sorted before
NodeKey { version: 0, nibble_path: f }
even though the latter is the rightmost leaf node.

Suggestion:
To ensure that the correct rightmost leaf node is retrieved, a possible solution is to adjust
the order of the fields in NodeKey by swapping nibble_path and version. This
adjustment will prioritize sorting by nibble_path first, followed by version. This
approach will ensure the correct rightmost leaf node is found. This change would require
further detailed testing and analysis to confirm its effectiveness.

**Comment by l-monninger** [comment]
JMT is not in use.
