### ISSUE TITLE
ROC-3 Lack of Atomicity in Multiple Database Write Operations in RocksdbJmt handling methods

### ISSUE THREAD

**Issue by SA124** [movementlabsxyz/movement#326]
Severity: Informational
Discovery Methods: Manual Review
Status: Pending
Auditor: Movebit
Topic:Suzuka-only custom components

ROC-3 Lack of Atomicity in Multiple Database Write Operations in RocksdbJmt handling methods

Code Location:
protocol-units/storage/jelly-move/src/rocksdb.rs#96,108,188,204,206

Descriptions:
In the current implementation of the RocksdbJmt , the RocksdbJmt handling methods
write_node_batch, write_tree_update_batch, and purge_stale_nodes perform
multiple write operations to the database. However, these operations are not atomic,
meaning that if an error occurs during one of these write operations, it can leave the
database in an inconsistent state. Specifically, the issue arises because each method makes
multiple calls to delete_cf and put_cf without wrapping them in a batch operation to
ensure atomicity.

Suggestion:
To ensure atomicity and maintain database consistency, it is recommended to use RocksDB's
batch operations for all database writes within these methods. By grouping multiple write
operations into a single batch, we can guarantee that either all operations succeed or none
of them are applied, Thus ensuring the atomicity of operations.

**Comment by l-monninger** [comment]
JMT is not in use.
