### ISSUE TITLE
ROC-4 Inefficient Implementation of get_value_option Leading to Potential DOS Vulnerability

### ISSUE THREAD

**Issue by SA124** [movementlabsxyz/movement#327]
ROC-4 Inefficient Implementation of get_value_option Leading to Potential DOS Vulnerability

Severity: Informational
Discovery Methods: Manual Review
Status: Pending
Auditor: Movebit
Topic:Suzuka-only custom components

Code Location:
protocol-units/storage/jelly-move/src/rocksdb.rs#143

Descriptions:
The function get_value_option has an inefficient implementation that can lead to
potential Denial-of-Service (DOS) attacks. This function iterates backwards from
max_version down to 0 until it finds a value. This can be inefficient and poses a risk for
DOS attacks, especially if max_version is a large integer. The time complexity of the
function is directly proportional to max_version, making it vulnerable to excessive delays
when handling large version numbers.
In comparison, the implementation from the reference project does not iterate over
max_versions down to 0 but rather accesses the version history and iterates only within
the relevant versions.

Suggestion:
Instead of iterating through all versions from max_version down to 0 , consider
maintaining a version history that allows for efficient access and iteration.
Add input validation to ensure max_version is within an acceptable range, preventing
malicious actors from passing excessively large values.

**Comment by l-monninger** [comment]
JMT is not in use.
