### ISSUE TITLE
Transaction expired error

### ISSUE THREAD

**Issue by BlurryfaceZXC** [movementlabsxyz/movement#330]
**Describe the bug**
After any transaction initiation comes that error. Looks like RPC error. It says "Transaction Expired". With that error wallet can't initiate any transaction(wallet is funded with MOVE). I tried different ways - to delete browser, to use VPN, to update extension (razor wallet). to clear cookies, to initiate transaction on different websites or just in razor wallet (send function). Looks unfixible to me. There is a bunch of people in discord with the same problem. I had the same problem in the Pontem wallet (aptos mainnet) a while ago. Nothing helped me yet.
chain - Movement APTOS
wallet - RAZOR

**To Reproduce**
1. Initiate any transaction on Movement Aptos testnet (razor wallet)
2. See error

**Expected behavior**
fix that issue?

**Screenshots**
![Screenshot_4](https://github.com/user-attachments/assets/543774da-6173-4f75-a541-670088286503)

**Desktop (please complete the following information):**
 - OS:Windows
 - Browser Chrome
 - Version 127.0.6533.100

**Comment by bhenhsi** [comment]
Please open a new ticket if the issue persists.
