### ISSUE TITLE
`complete_bridge_transfer` should be Callable by any client. 

### ISSUE THREAD

**Issue by 0xmovses** [movementlabsxyz/movement#357]
## Summary
Currently in the module, both the `master_minter` and `client` are passed into the fn. Thanks @andyjsbell for finding. 
```
complete_bridge_transfer(
           client,
           bridge_transfer_id,
           pre_image,
           master_minter 
       );
```
## Requirements
- Update the module so that any client (that posses the correct secret) can call the function. 
- Write a unit test to prove this.

**Comment by andygolay** [comment]
Just noticed this is the case on the initiator side as well:

```move
    public fun complete_bridge_transfer(
        account: &signer,
        bridge_transfer_id: vector<u8>,
        pre_image: vector<u8>,
        atomic_bridge: &signer
```

However, is the bridge supposed to be calling `complete_bridge_transfer` to burn the MovETH? If the bridge is the caller then it's an easier cleanup and I'm not sure that a resource account would be needed.
