### ISSUE TITLE
Fix flaky bridge test case `test_movement_client_should_build_and_fund_accounts`

### ISSUE THREAD

**Issue by 0xmovses** [movementlabsxyz/movement#379]
## Description
Locally this test was passing for me pretty consistently, then it started failing and when it's ran in CI it fails with: 

The CI check fails with the error 
`Failed to create MovementClient: No such file or directory (os error 2)`

clippy was giving a warning about it also, (which we were not seeing before due to the analyzer problem we had last week:
```rust
clippy: this MutexGuard is held across an await point
consider using an async-aware Mutex type or ensuring the MutexGuard is dropped before calling await
for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#await_holding_lock
#[warn(clippy::await_holding_lock)] on by default [await_holding_lock]
```

I removed it from the feature branch here for now, just so we can prioritise merged this branch 
https://github.com/movementlabsxyz/movement/pull/215/commits/cbda177177a0f91df63f8bbf278875f82cc22c0a

## Requirements 
The removed test, should pass consistently locally and in CI.

**Comment by andygolay** [comment]
Thanks, will get to this after finishing the integration tests. Got kind of blocked on the publishing under resource account but got it working now and finishing the other tests.

**Comment by 0xmovses** [comment]
Ah yes, our favourite aptos-move pattern ;) No worries at all. As we have built our own `TestHarness` for the atomic bridge and its not been heavily used yet, there are bound to be tweaks needed for it.
