### ISSUE TITLE
Aptos Suzuka  (error 400)

### ISSUE THREAD

**Issue by hazydazy555** [movementlabsxyz/movement#392]
Aptos movement. Already tried to change rpc, wallets, browser, reinstall. Nothing helps. 

Here is an error from console:

       Failed to load resource: the server responded with a status of 400 ()
utils-ChQnBPug.js:464 Uncaught (in promise) AptosApiError: Fullnode error: {"message":"Invalid transaction: Type: Validation Code: TRANSACTION_EXPIRED","error_code":"vm_error","vm_error_code":6}
    at N$6 (utils-ChQnBPug.js:464:1633)
    at async B$1 (utils-ChQnBPug.js:464:774727)
    at async inject.ts-ekQYKCqJ.js:3:6252

**Comment by anujwithmovemnets** [comment]
it is happening with me too , every quest that includes movement aptos is showing movement aptos

**Comment by l-monninger** [comment]
Can you provide code to
