### ISSUE TITLE
MOD-1 Lack of Garbage Collection Mechanism in Movement-Aptos-Core's Mempool

### ISSUE THREAD

**Issue by SA124** [movementlabsxyz/movement#411]
MOD-1 Lack of Garbage Collection Mechanism in Movement-Aptos-Core's Mempool
Auditor: Movebit
Code: Aptos Core
Severity: Major
Discovery Methods: Manual Review
Status: Pending
Code Location:
protocol-units/execution/opt-executor/src/executor/mod.rs#59

Descriptions:
A complete mempool should have a garbage collection mechanism, also known as a
transaction aging mechanism, which periodically removes expired and unused transactions to
prevent the mempool from growing indefinitely.
Aptos's garbage collection code is as follows:

![Screenshot 2024-08-21 at 10 55 53 AM](https://github.com/user-attachments/assets/af7b19af-3326-4e31-9b8a-2124c7d082f8)

Suggestion:
It is recommended to enable Aptos's mempool garbage collection feature.

**Comment by l-monninger** [comment]
https://github.com/movementlabsxyz/movement/blob/31386f74a2700920fec093775c221acdc9c6c7a2/protocol-units/execution/opt-executor/src/transaction_pipe.rs#L112
