### ISSUE TITLE
TPI-1 Invalid sequence_number Check for Mempool in aptos-core

### ISSUE THREAD

**Issue by SA124** [movementlabsxyz/movement#415]
TPI-1 Invalid sequence_number Check for Mempool in aptos-core

Auditor: Movebit
Code: Aptos Core
Severity: Informational
Discovery Methods: Manual Review
Status: Pending
Code Location:
protocol-units/execution/opt-executor/src/executor/transaction_pipe.rs#61-67
Descriptions:
Transactions are added to core_mempool after they have been pre-executed:

<img width="532" alt="Screenshot 2024-08-21 at 11 09 20 AM" src="https://github.com/user-attachments/assets/ed70e1b6-a2fc-49d1-9c05-74e5faa8e28b">

The join is checked against the sequence_number of the joining transaction:

<img width="532" alt="Screenshot 2024-08-21 at 11 09 49 AM" src="https://github.com/user-attachments/assets/28738a3b-a8f1-45e4-8764-6014d5a96cf0">

Since the db_sequence_number passed in is transaction.sequence_number, this check does
not work, but it is not harmful because of the pre-execution check that was performed
earlier.
Suggestion:
Change the incoming parameter to the real db_sequence_number.

**Comment by l-monninger** [comment]
#494
