### ISSUE TITLE
In setGenesisCeremony the code confuses the genesis amount with the staked amount, causing the StakeExceedsGenesisStake check to be reversed. 

### ISSUE THREAD

**Issue by SA124** [movementlabsxyz/movement#418]
Auditor: Ottersec
Code: MCR Contract 

Issue that we believe could lead to loss of funds:
In setGenesisCeremony the code confuses the genesis amount with the staked amount, causing the StakeExceedsGenesisStake check to be reversed. This leads to loss of funds since the refund formula is also reversed. Attacker can create their own “domain”, call setGenesisCeremony, and withdraw tokens from the underlying vault (which is shared across domains).

**Comment by l-monninger** [comment]
The `setGenesisCeremony` function has been removed since this was reviewed. It was for development and speculative use cases that were never defined as requirements.

**Comment by SA124** [comment]
<img width="411" alt="Screenshot 2024-08-22 at 2 50 10 PM" src="https://github.com/user-attachments/assets/7b30f831-229d-43ed-a659-8fa0e8f357d8">
<img width="351" alt="Screenshot 2024-08-22 at 2 50 26 PM" src="https://github.com/user-attachments/assets/afc9baf9-f6ae-4c2e-a866-974f161da593">
<img width="354" alt="Screenshot 2024-08-22 at 2 50 40 PM" src="https://github.com/user-attachments/assets/859f3faf-e0e3-40d8-b2bc-4187dcc9b225">
<img width="353" alt="Screenshot 2024-08-22 at 2 50 52 PM" src="https://github.com/user-attachments/assets/492a2a72-96dd-44f5-a41e-2090e9d0e6f1">
<img width="352" alt="Screenshot 2024-08-22 at 2 51 04 PM" src="https://github.com/user-attachments/assets/3682e638-b247-45e5-b755-273f581187e1">
<img width="352" alt="Screenshot 2024-08-22 at 2 51 17 PM" src="https://github.com/user-attachments/assets/9925a9ab-c9ec-4851-8c88-93cd419b6a71">

@l-monninger

**Comment by l-monninger** [comment]
Again, this has already been removed: https://github.com/movementlabsxyz/movement/blob/main/protocol-units/settlement/mcr/contracts/src/settlement/MCR.sol
