### ISSUE TITLE
MST-1 stake Didn't Limit The Type of custodian

### ISSUE THREAD

**Issue by SA124** [movementlabsxyz/movement#449]
MST-1 stake Didn't Limit The Type of custodian

Auditor: Movebit
Code: MCR Settlement Contract
Severity: Major
Status: Pending

Code Location:
protocol-units/settlement/mcr/contracts/src/staking/MovementStaking.sol#273

Descriptions:
Users with the WHITELIST_ROLE privilege can call the stake function to stake their
stake token. However, there is no restriction on the type of custodian tokens,
resulting in users being able to pass in worthless erc20 tokens and subsequently pay a small
amount of stake token to the Staking contract making the if statements on line 292
unequal, resulting in users being able to increase the number of stake at will.
Suggestion:
It is recommended to use whitelist mode for custodian tokens.

**Comment by l-monninger** [comment]
The checks referenced require that the custodian does indeed transfer a valid amount of the underlying token: https://github.com/movementlabsxyz/movement/blob/31386f74a2700920fec093775c221acdc9c6c7a2/protocol-units/settlement/mcr/contracts/src/staking/MovementStaking.sol#L277

We are checking that the balance of the underlying token, `token`,  is increased by the staked amount, `amount`, after a transfer is made via the custodian, `custodian`.
