### ISSUE TITLE
Tighten Module Move Error Assertions

### ISSUE THREAD

**Issue by 0xPrimata** [movementlabsxyz/movement#458]
**Is your feature request related to a problem? Please describe.**
Currently most of the Bridge Move Module tests are expecting any error. This leads to unexpected errors also being caught as a valid error and our tests becoming meaningless.

**Describe the solution you'd like**
1. Specify errors with correct, specific abort_codes ([expected_failure (abort_code = n)]
2. Expect a single error per test

**Describe alternatives you've considered**

**Additional context**

**Comment by 0xmovses** [comment]
Merged in #478
