### ISSUE TITLE
Channel infinitely growing with transactions

### ISSUE THREAD

**Issue by SA124** [movementlabsxyz/movement#492]
Severity:[LOW] 
Auditor: Halborn
Code: Suzuka

Channel infinitely growing with transactions
The Suzuka full node creates a channel that is only used by the tick transaction pipe function, that sends each processed transaction, leading to the channel increasing in size:
[protocol-units/execution/opt-executor/src/executor/transaction_pipe.rs#L79](https://github.com/movementlabsxyz/movement/blob/030fe011da8bd7eca75fa0a37197205767bef7ec/protocol-units/execution/opt-executor/src/executor/transaction_pipe.rs#L79)
Channel with no consumer created in [networks/suzuka/suzuka-full-node/src/partial.rs#L304](https://github.com/movementlabsxyz/movement/blob/030fe011da8bd7eca75fa0a37197205767bef7ec/networks/suzuka/suzuka-full-node/src/partial.rs#L304)

**Comment by l-monninger** [comment]
I believe this is a quirk of being in between two approaches at the audited commit height. It no longer exists as such.
