### ISSUE TITLE
CAR-1 Code error causes normal functionality failure 

### ISSUE THREAD

**Issue by SA124** [movementlabsxyz/movement#507]
CAR-1 Code error causes normal functionality failure 

Auditor: Movebit
Code: Atomic Bridge
Level: Informational
Code Location: protocol-units/bridge/chains/ethereum/src/event_logging.rs#56

<img width="947" alt="Screenshot 2024-09-03 at 12 10 21 PM" src="https://github.com/user-attachments/assets/bc2a8b15-bb0e-4f64-a573-2c64dd17a6b2">

**Comment by 0xmovses** [comment]
This has been updated and is resolved in the new event monitoring implementation.
