### ISSUE TITLE
BSE-1 BridgeService Lacks Restart Recovery Mechanism 

### ISSUE THREAD

**Issue by SA124** [movementlabsxyz/movement#508]
BSE-1 BridgeService Lacks Restart Recovery Mechanism 

Auditor: Movebit
Code: Atomic Bridge 
Level: Major
Code Location: protocol-units/bridge/shared/src/bridge_service.rs#140

<img width="940" alt="Screenshot 2024-09-03 at 12 26 28 PM" src="https://github.com/user-attachments/assets/1d7c97b0-38d2-4c32-a420-4ccb59c2b887">

**Comment by 0xmovses** [comment]
We have implemented a data store where current or active transfers are written to disk, the events are picked up and continued if the service is restarted. Upon observing this in testnet under high load, more optimisations to this mechanism can be made.
