### ISSUE TITLE
BSE-2 Two Poll:: Ready Calls could cause critical event loss 

### ISSUE THREAD

**Issue by SA124** [movementlabsxyz/movement#510]
BSE-2 Two Poll:: Ready Calls could cause critical event loss 

Auditor: Movebit
Code: Atomic Bridge
Level: Major
Code Location: protocol-units/bridge/shared/src/blockchain_service.rs#45

<img width="496" alt="Screenshot 2024-09-03 at 12 36 07 PM" src="https://github.com/user-attachments/assets/1394ff0d-4d71-4fb1-b59e-5036b34ca8b5">

**Comment by 0xmovses** [comment]
We now query the blockchain directly via RPC queries, not WS events which could be deemed unstable. Also this particular part of code has been refactored for the new event monitoring.
