### ISSUE TITLE
ABI-2 Time_lock can be set to 0

### ISSUE THREAD

**Issue by SA124** [movementlabsxyz/movement#513]
ABI-2 Time_lock can be set to 0

Auditor: Movebit
Code: Atomic Bridge
Level: Critical
Code Location: protocol-units/bridge/contracts/src/AtomicBridgeInitiator.sol#47
<img width="748" alt="Screenshot 2024-09-03 at 12 43 59 PM" src="https://github.com/user-attachments/assets/df98fd8e-1f47-48fe-a492-c12f545c8be8">

protocol-units/bridge/move-modules/sources/atomic_bridge_initiator.move#83

**Comment by 0xmovses** [comment]
Timelocks are now set during initialisation of the contract and remain constant
