### ISSUE TITLE
ABC-1 abortBridgeTransfer has no Access Control 

### ISSUE THREAD

**Issue by SA124** [movementlabsxyz/movement#514]
Auditor: Movebit
Code: Atomic Bridge
Level: Medium

<img width="699" alt="Screenshot 2024-09-03 at 12 46 00 PM" src="https://github.com/user-attachments/assets/626e0972-0ced-41db-a83a-dd393eb829cf">

**Comment by 0xmovses** [comment]
These functions are now protected with `onlyOwner`.
