### ISSUE TITLE
ABC-2 Lack of Events Emit

### ISSUE THREAD

**Issue by SA124** [movementlabsxyz/movement#515]
Auditor: Movebit
Code: Atomic Bridge
Level: Informational
<img width="740" alt="Screenshot 2024-09-03 at 12 48 40 PM" src="https://github.com/user-attachments/assets/cd00fe17-abbb-4d4a-8658-80cd4a8fac75">

Suggestion: Modify code

**Comment by 0xmovses** [comment]
This function has been removed in favour of these contracts inheriting openzeppelin's `OwnableUpgradeable.sol`
