### ISSUE TITLE
ABC1-2 complete_bridge_transfer Function Missing timeLock Check 

### ISSUE THREAD

**Issue by SA124** [movementlabsxyz/movement#518]
Auditor: Movebit
Severity: Major
Code: Atomic Bridge

<img width="736" alt="Screenshot 2024-09-03 at 1 01 47 PM" src="https://github.com/user-attachments/assets/04a21707-0443-4c7a-8581-7ee862ae10da">

**Comment by 0xmovses** [comment]
These have been added
