### ISSUE TITLE
ABC-1-3 Hard Code Error Code 

### ISSUE THREAD

**Issue by SA124** [movementlabsxyz/movement#519]
Auditor: Movebit
Severity:Informational 
Code: Atomic Bridge

<img width="758" alt="Screenshot 2024-09-03 at 1 02 40 PM" src="https://github.com/user-attachments/assets/b9d31321-5c89-475a-bbd9-1806c013d00a">

**Comment by 0xmovses** [comment]
These contracts are being deprecated for the new framework code https://github.com/movementlabsxyz/aptos-core/blob/movement/aptos-move/framework/aptos-framework/sources/atomic_bridge.move
