### ISSUE TITLE
Investigate transaction replay handling in aptos-executor

### ISSUE THREAD

**Issue by mzabaluev** [movementlabsxyz/movement#526]
Discussion: #475

As part of addressing #416, check the cost of trying to execute a replayed transaction in the extant aptos-executor code.
The ideal outcome is that the execution is cheap (i.e. incurs negligible costs to node operators) and incurs no losses in gas fees to the signer of the original transaction.

**Comment by l-monninger** [comment]
@mzabaluev How goes here?

**Comment by l-monninger** [comment]
> [https://github.com/movementlabsxyz/aptos-core/blob/8daa93581c9334e4ef6ad4df9657819[…]e/framework/aptos-framework/sources/transaction_validation.move](https://github.com/movementlabsxyz/aptos-core/blob/8daa93581c9334e4ef6ad4df96578194d7eca7f6/aptos-move/framework/aptos-framework/sources/transaction_validation.move#L109) (edited)

Yes, but that's in the prologue for the transaction, so it gets aborted and the gas fee is charged.

**Comment by l-monninger** [comment]
What we want here is to prevent replay attacks, which means accounting for sending the same transaction before the transaction enters stages of execution where it would be aborted and gas fees would be charged.
