### ISSUE TITLE
MST-7 acceptGenesisCeremony Function Can Be Called Multiple Times

### ISSUE THREAD

**Issue by SA124** [movementlabsxyz/movement#529]
MST-7 acceptGenesisCeremony Function Can Be Called Multiple Times
Auditor: Movebit
Code: MCR Settlement Contract
Severity: Discussion
Status: Pending

Code Location:
protocol-units/settlement/mcr/contracts/src/staking/MovementStaking.sol#61

Descriptions:
The acceptGenesisCeremony function does not check to see if it has already been called, so it can be called multiple times by the domain causing an error in the number of stakes recorded for the attester.

Suggestion:
It is recommended to check that the function has been called by a domain.

**Comment by l-monninger** [comment]
See comment on #536
