### ISSUE TITLE
MCR1-1 unstake Logic Error

### ISSUE THREAD

**Issue by SA124** [movementlabsxyz/movement#530]
MCR1-1 unstake Logic Error
Auditor: Movebit
Code: MCR Settlement Contract 
Severity: Major
Status: Pending

Code Location:
protocol-units/settlement/mcr/contracts/src/MCRLegacy.sol#248

Descriptions:
The unstake function does not check that the argument amount is greater than the
current epochStakes and the next epoch of epochUnstakes , resulting in the user being able to call the unstake function twice to make the number of epochUnstakes greater than the epochStakes .

Suggestion:
It is recommended to consider the number of users that have unstaked.

**Comment by mzabaluev** [comment]
The `MCRLegacy.sol` script is no longer in use and will be removed in #537.
