### ISSUE TITLE
Finding difficult to connect galxe account to MOVEMENT LABS

### ISSUE THREAD

**Issue by Sirdecent2000** [movementlabsxyz/movement#548]
I have been consistently unable to connect my galxe account to movement labs...

**To Reproduce**
1. Go to movement labs testnet site
2.  Click on connect "galxe"
3. log in with your galxe account
4. Taking log time to connect and eventually bring server error

**server error"

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [window]
 - Browser [chrome
![movement labs galxe error](https://github.com/user-attachments/assets/8abc2984-ac5d-4d3c-ad91-d770a7eeee2a)
![movement labs galxe error](https://github.com/user-attachments/assets/f33c577d-825f-4e8a-b9e3-53e5bfad580c)
]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Khan-arsh** [comment]
@Sirdecent2000 Thanks for posting the issue. 

Your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support : [Help Center](https://cryptorectification.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**
