### ISSUE TITLE
(HAL-17) BRIDGE SERVICE STUCK WHILE POLLING SIMULTANEOUS EVENTS

### ISSUE THREAD

**Issue by SA124** [movementlabsxyz/movement#581]
(HAL-17) BRIDGE SERVICE STUCK WHILE POLLING SIMULTANEOUS EVENTS

Auditor: Halborn
Severity: Medium

Description
The blockchain service's poll_next_event function may enter a deadlock state, returning Pending indefinitely even when events are available for processing, essentially freezing the bridge.

The issue stems from the simultaneous polling of initiator and counterparty events:

![Screenshot 2024-09-12 at 11 24 01 AM](https://github.com/user-attachments/assets/22b768ee-d91c-41bd-a55f-28cef08e9ab4)
![Screenshot 2024-09-12 at 11 24 36 AM](https://github.com/user-attachments/assets/d11c257c-fa77-4393-b45a-bc14b4f257f7)

BVSS
[AO:A/AC:L/AX:L/R:P/S:U/C:N/A:C/I:N/D:C/Y:N (6.3)](https://www.halborn.com/bvss?q=AO%3AA%2FAC%3AL%2FAX%3AL%2FR%3AP%2FS%3AU%2FC%3AN%2FA%3AC%2FI%3AN%2FD%3AC%2FY%3AN)

![Screenshot 2024-09-12 at 11 25 33 AM](https://github.com/user-attachments/assets/a8d618af-daf7-43f0-8870-8a31d2867ab2)

Recommendation
It is recommended to handle the case where both events are polled.

**Comment by 0xmovses** [comment]
This logic has been refactored and the issue no longer exists, cc. @musitdev
