### ISSUE TITLE
(HAL-02) USE OF WRONG ERROR MESSAGES

### ISSUE THREAD

**Issue by SA124** [movementlabsxyz/movement#590]
(HAL-02) USE OF WRONG ERROR MESSAGES

Auditor: Halborn
Severity: Informational

Description
MCR SENDS WRONG ERROR MESSAGE ON BLOCK ALREADY COMMITED
In the MCR.sol contract, the error message returned when the proposed block commitment height is behind the tolerable block height is AttesterAlreadyCommitted which can be confusing, as it is not describing the issue and is also used for when the attester tries to submit the same block commitment twice.

![Screenshot 2024-09-12 at 12 19 33 PM](https://github.com/user-attachments/assets/dfd6417e-d279-4ddd-879c-c421cd03e730)

Recommendation
It is recommended to:

Replace the MCR error message by a more understandable message such as BlockCommitmentTooFarAhead.
Replace the Bridge error message by a more understandable message such as TimeLockNotExpired.

**Comment by 0xmovses** [comment]
Fixed in https://github.com/movementlabsxyz/movement/pull/693
