### ISSUE TITLE
 (HAL-22) BRIDGE UNUSED AND INCOMPLETE TRACKING OF BALANCES

### ISSUE THREAD

**Issue by SA124** [movementlabsxyz/movement#592]
(HAL-22) BRIDGE UNUSED AND INCOMPLETE TRACKING OF BALANCES

Auditor: Halborn
Severity: INFORMATIONAL

Description
The following snippet in the counterparty_contract.rs file contains logic that is not used anywhere else in the codebase:

![Screenshot 2024-09-12 at 12 22 37 PM](https://github.com/user-attachments/assets/6f067fcc-6338-48f8-8ec6-f718ec0d7982)

Score
[AO:A/AC:L/AX:L/R:N/S:U/C:N/A:N/I:N/D:N/Y:N (0.0)](https://www.halborn.com/bvss?q=AO%3AA%2FAC%3AL%2FAX%3AL%2FR%3AN%2FS%3AU%2FC%3AN%2FA%3AN%2FI%3AN%2FD%3AN%2FY%3AN)

![Screenshot 2024-09-12 at 12 23 05 PM](https://github.com/user-attachments/assets/2d2169d1-0406-4216-926a-e6aac6698cf7)

Recommendation
It is recommended to assess whether the code snipped is necessary and remove it if not needed.

**Comment by 0xmovses** [comment]
This part of the codebase has been refactored and removed. This can be closed.
