### ISSUE TITLE
(HAL-30) TEST ROLL OVER GENESIS FUNCTION USED IN PRODUCTION

### ISSUE THREAD

**Issue by SA124** [movementlabsxyz/movement#595]
(HAL-30) TEST ROLL OVER GENESIS FUNCTION USED IN PRODUCTION
Auditor: Halborn
Severity: Informational

![Screenshot 2024-09-12 at 12 33 24 PM](https://github.com/user-attachments/assets/62ec47f0-3b09-4b5f-a771-d5c3bd464597)

This misuse of a testing function could lead to unexpected behavior, potential security vulnerabilities, and inconsistencies in the blockchain's initial state.

Score
[AO:A/AC:L/AX:L/R:N/S:U/C:N/A:N/I:N/D:N/Y:N (0.0)](https://www.halborn.com/bvss?q=AO%3AA%2FAC%3AL%2FAX%3AL%2FR%3AN%2FS%3AU%2FC%3AN%2FA%3AN%2FI%3AN%2FD%3AN%2FY%3AN)

![Screenshot 2024-09-12 at 12 33 58 PM](https://github.com/user-attachments/assets/f4e9e991-1aa9-4b4e-b846-296299d5c72e)

Recommendation
It is recommended to assess whether the function is suitable for production use, and keep or change it if needed.

**Comment by l-monninger** [comment]
We've assessed this a few times and believe it is safe for our purely execution-based used case. We would, however, like to re-evaluate the use of genesis key before Suzuka Genesis.

**Comment by l-monninger** [comment]
We've modified the manner in which we compute attestations, so this needs to be updated. I am adding determinism and checks for consistency.
