### ISSUE TITLE
GATEWAY TIME OUT

### ISSUE THREAD

**Issue by mosby4700** [movementlabsxyz/movement#635]
**Describe the bug**

**To Reproduce**
1. Go to (https://testnet.movementlabs.xyz/)
2. Click on 'Connect galxe'
3. redirects to 'Galxe webpage for authorization'
4. Click Authorize
5. Gateway timeout
6. 
![Screenshot 2024-09-27 184012](https://github.com/user-attachments/assets/52887dd8-703b-4c70-ba18-5dc26d895efb)

**Expected behavior**
seamless connection between galxe and movement

**Screenshots**

**Desktop (please complete the following information):**
 - Browser [chrome,]
   Version 129.0.6668.70 (Official Build) (64-bit)

**Comment by Chibenz** [comment]
![17292568688425994506024835570061](https://github.com/user-attachments/assets/9a465752-bc3c-460a-a23a-26bf977f305e)
When I try to authorise my galxe it takes me to this error page

**Comment by bhenhsi** [comment]
The Intermittent outage has been resolved. Please report parthenon issues in Discord. This repo is for the Movement network protocol.
