### ISSUE TITLE
Replace uses of `async_channel`

### ISSUE THREAD

**Issue by mzabaluev** [movementlabsxyz/movement#64]
Consider replacing uses of MPMC channels from `async_channel` with more lightweight MPSC channels such as `tokio::sync::mpsc`.

There is hardly ever a genuine need to have multiple receivers on the channel. In many cases, cloning of the receiver has been a solution to the somewhat arbitrary constraints on higher-level API. So the solution will involve some rearchitecting.

_Originally posted by @mzabaluev in https://github.com/movementlabsxyz/movement/pull/58#discussion_r1601170509_

**Comment by JoeruCodes** [comment]
Would wrapping the receiver with Arc (for cloning) and RwLock (for allowing mutations required by the .recv() method of tokio::mpsc without needing &mut self, which was causing issues with mutable and immutable borrows in the same scope) allow us to replace async::channel with Tokio's mpsc? Or maybe something like broadcast streams should also be an effective solution for it, without needing much rearchitecting stuff around...

**Comment by mzabaluev** [comment]
A redesign to remove `Arc` and interior-mutable state in #63 should remove most of the need for cloned receivers. `async_channel` does not do broadcast, there needs to be a different solution for this if it's needed at all, possibly in the form of a pub-sub message bus.

**Comment by JoeruCodes** [comment]
I see! I did go through the proposals of that issue but we might still need mpscs for the supervisor node right?

Tokio does have broadcast channel but even that is a bounded mpsc (we are using unbounded mpscs currently bounded mpscs may require some handling) which might be as heavy as using async channel's mpsc...

**Comment by mzabaluev** [comment]
`async_channel` is gone with #308.
