### ISSUE TITLE
Movement Labs Testnet Faucet Error

### ISSUE THREAD

**Issue by hien17** [movementlabsxyz/movement#654]
`**Description**`
Unable to fund new account on Movement Labs testnet due to a 403 Forbidden error from the faucet service.

**To Reproduce**
```
aptos init --network custom \
  --rest-url https://aptos.testnet.suzuka.movementlabs.xyz/v1 \
  --faucet-url https://faucet.testnet.suzuka.movementlabs.xyz/

```
**Actual Result**
```

{
  "Error": "API error: Faucet issue: FaucetClientError { 
    inner: Inner { 
      kind: HttpStatus(403), 
      source: None 
    } 
  }"
}

```
**Screenshots**
![image](https://github.com/user-attachments/assets/3b9f4934-8e94-45de-b73b-647e00ba162e)

**Expected behavior**

Account should be created and funded with 100000000 Octas.

**Environment**

Aptos CLI version: 4.2.3

**Comment by l-monninger** [comment]
The faucet endpoint is not intended to be publicly available.
