### ISSUE TITLE
In path of Guilds - error with quest - bad link!

### ISSUE THREAD

**Issue by XanderNod** [movementlabsxyz/movement#657]
**Describe the bug**

**In path of Guilds - error with quest - bad link!**
1. Go to '[...](https://testnet.movementlabs.xyz/guilds)'
2. Click on 'Explorers Guild' and choose 3rd quest - link error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
![11](https://github.com/user-attachments/assets/039f96c9-5963-4944-8283-3ba80f75322c)

**Comment by bhenhsi** [comment]
I will share this with the Parthenon team; for future Parthenon bugs, please report them on Discord.
