### ISSUE TITLE
Cannot get blob from S3 bucket when spinning up a Movement Follower Node

### ISSUE THREAD

**Issue by ivanpeng-sh** [movementlabsxyz/movement#680]
**Describe the bug**
I'm following the instructions [here](https://github.com/movementlabsxyz/movement/blob/main/docs/movement-node/run/manual/follower-node/README.md) to start a follower node in my local environment, and it seems there are some permission issues when getting the snapshot from S3. From the setup container logs:

```
setup                       | 2024-10-10T16:01:35.607535Z  INFO syncador::backend::s3::shared_bucket::pull: Downloading all files for candidate: Candidate { key: "1a2b3c4d5e6f7a8b9cadbecfd0e1f2031425364758697a8b9cadbecfd0e1f203/f611b522d870b05525d91d60a2072fc20ce82e33c980790dce25ba522dffc0f6/1728576000000", sync_epoch: 1728576000000 }
setup                       | Error: Backend Error: service error
setup                       |
setup                       | Caused by:
setup                       |     0: service error
setup                       |     1: unhandled error (AccessDenied)
setup                       |     2: Error { code: "AccessDenied", message: "Access Denied", aws_request_id: "PN8M8RSAKX2EB99R", s3_extended_request_id: "98Lix4NLyi6VsmrWJCvNsRoiKympwm8mo46IeJf2/vHNYSGcicYnejj3hKCphYevf5OyWRke1i0=" }
Gracefully stopping... (press Ctrl+C again to force)
```

Furthermore, I verified via AWS CLI that I cannot get objects from the bucket:
```
(nix:nix-shell-env) Ivans-MacBook-Pro:movement ivanpeng$ aws s3 cp --no-sign-request  s3://mtnet-l-sync-bucket-sync/1a2b3c4d5e6f7a8b9cadbecfd0e1f2031425364758697a8b9cadbecfd0e1f203/56f6b1ad73e4ca5a8e0f7c59788aa4e780fd45cb07e65214ecb4205fa15739ac/1728576720000/0.tar.gz .
fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden
```

I think a few extra permissions are required on the public bucket for objects to be pulled from it.

**Expected behavior**
The setup container for a movement node should be able to get and download objects from S3.

**Comment by l-monninger** [comment]
@ivanpeng-sh 

1. Check now. I attached a new ownership policy.
2. Do you have the AWS region set to `us-west-1`?

**Comment by ivanpeng-sh** [comment]
Hi Liam, I just tried again, and unfortunately I still do not have permissions:
```
(nix:nix-shell-env) Ivans-MacBook-Pro:movement ivanpeng$ aws --region us-west-1 s3 cp s3://mtnet-l-sync-bucket-sync/1a2b3c4d5e6f7a8b9cadbecfd0e1f2031425364758697a8b9cadbecfd0e1f203/56f6b1ad73e4ca5a8e0f7c59788aa4e780fd45cb07e65214ecb4205fa15739ac/1728579960000/0.tar.gz . 
fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden
```

**Comment by l-monninger** [comment]
Okay, had the chance to reproduce without an account outside our org. Definitely not available, I must have fat fingered something in the last couple rounds of infra applies. Updating shortly.

**Comment by l-monninger** [comment]
@ivanpeng-sh should be fixed now.

**Comment by ivanpeng-sh** [comment]
Yep, confirming it works now. Closing this issue. Thanks for the resolution!

**Comment by xinzhongyoumeng** [comment]
Excuse me, we see the similar problem, can you tell me the corrent vars, if we deploy the mainnet node for move.
MOVEMENT_SYNC
AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY
AWS_REGION
