### ISSUE TITLE
Wallet connection issue

### ISSUE THREAD

**Issue by herbcase** [movementlabsxyz/movement#708]
1) I installed the Nightly wallet and Razor wallet, but they show up as not installed on the MOVEMENT Dapps site, including faucet.
![image](https://github.com/user-attachments/assets/a0e1c699-a9cf-4105-a7e8-ef86b4693497)

2) For the above reason, I tried to replace it with the OKX wallet, but the MOVE balances of the Nightly wallet and OKX wallet are displayed differently even though they are the same wallet address.
![image](https://github.com/user-attachments/assets/494795da-5f18-4d72-88c0-f4bdfba8243a)
![image](https://github.com/user-attachments/assets/ed5583dd-d4c3-411e-8e35-7293993ce17e)

**Comment by herbcase** [comment]
For reason 1, I continued deleting Chrome browser cookies and reinstalling the app, but it failed.

**Comment by bhenhsi** [comment]
Please reach out to the Nightly and Razor Wallet team for support.
