### ISSUE TITLE
[Feature Request] Add Additional Indexer Processors 

### ISSUE THREAD

**Issue by shayansanjideh** [movementlabsxyz/movement#759]
**Is your feature request related to a problem? Please describe.**
Builders have reported that they are unable to use certain queries on Movement, when they are able to use them on Aptos. For example:

> I created an NFT Collection using the Digital Asset Standard but I'm not able to query the data:
> This is my account:
> https://explorer.testnet.porto.movementnetwork.xyz/account/0x7a377968cb92784e66ad39b0e6be2cd10e0843d9ea72a6b9b3b5bfb051872bf6/transactions?network=testnet
> This is the collection:
> https://explorer.testnet.porto.movementnetwork.xyz/object/0x323f7c341d2fdfda5c5dfefb1b51cad9063a0ad599fdc716ba12fea528510c5b/resources?network=testnet
> This is an example NFT Mint Transaction:
> https://explorer.testnet.porto.movementnetwork.xyz/txn/0xc6a634b2c2ec7c18a9fbad97ba0f992ed9ebe9e4d89e608091aae30f7a84f391?network=testnet
> This is a query to try to read nfts from the collection:
```
query GetCollectionNfts($collectionId: String!) {
 current_token_datas_v2(where: {
   collection_id: {
    _eq: $collectionId
   }
 }, limit: 100, offset: 0) {
  token_name
 }
}
using params like:
{
 "collectionId": "0x323f7c341d2fdfda5c5dfefb1b51cad9063a0ad599fdc716ba12fea528510c5b"
}
```

Philippe stated the following:

> I think it's because the NftMetadataProcessor is not started. Some processor need some specific configuration to be started. Currently the stared processor are:
```
usertx_indexer
accounttx_indexer
coin_indexer
event_indexer
fungible_indexer
txmeta_indexer
```
> Other processor can be started. The ones provided by Aptos and not started are:
```
NftMetadataProcessor,
ObjectsProcessor,
StakeProcessor,
TokenProcessor,
TokenV2Processor,
```
> One thing to know is that more processor are started more load is apply on the Proto node.
> Last there's some specific processor that need more work and that I don"t know for what they are provided:
```
ParquetDefaultProcessor,
ParquetFungibleAssetProcessor,
```

**Describe the solution you'd like**
It would be optimal to get the other processors started. Since this can be a significant engineering feat, I will update this issue with additional requests as they come in, so we can assess them on a case-by-case basis.

**Comment by musitdev** [comment]
I've studied the processor related to NFC. There's 3:
```
TokenProcessor,
TokenV2Processor,
NftMetadataProcessor
```
The first two processors update the indexer DB like the other for token-related data.
The last one, `NftMetadataProcessor,` parses the Tx the same way as the TokenProcessor but doesn't write to the indexer DB. Instead, it sends the data to Google Cloud storage, for which I don't have a reference.
I can activate the first 2 because they are similar to the others. For the `NftMetadataProcessor` I need more info about the cloud storage.

Last point the `TokenProcessor` takes an optional parameter: `nft_points_contract`. Do we need it? If yes I need the address.

**Comment by movement-overdrive** [comment]
You did not activate TokenV2Processor yet, right? At least I still get empty responses.
Let me know when it's activated. I can test it from my side and give you feedback.
