### ISSUE TITLE
Call `completeBridgeTransfer` successfully on the ETH side 

### ISSUE THREAD

**Issue by andygolay** [movementlabsxyz/movement#780]
**Is your feature request related to a problem? Please describe.**

The bridge front-end has successfully called `lockBridgeTransfer` (see https://holesky.etherscan.io/address/0x5b97cdf756f6363a88706c376464180e008bd88b)

but the `completeBridgeTransfer` call is failing. 

Manually test `completeBridgeTransfer` calls using `cast` and to debug, then fix in https://github.com/movementlabsxyz/bridge-interface or https://github.com/movementlabsxyz/movement depending on where the cause of the error is.

**Comment by 0xmovses** [comment]
Closing as duplicate.
