### ISSUE TITLE
Bridge relayer fails to lock old but still pending transfers on L2

### ISSUE THREAD

**Issue by andygolay** [movementlabsxyz/movement#806]
If a bridge transfer is initiated on L1 and the relayer fails to pick up the event (see screenshot with an example of bridge-service logs when `get_account_events` fails:
![image](https://github.com/user-attachments/assets/e3a92f1c-7121-4463-af99-b19e0e79a16f)

In this case, we are left with several pending transfers:
![image](https://github.com/user-attachments/assets/ef5198ef-aa9a-412f-b02e-cbf12d73a09b)

The above transfers were in that state for about 24 hours before the screenshot, and it doesn't appear that the relayer will ever call `lock_bridge_transfer` on the L2 for them.

From what I can tell this may be due to the code
```
		//read the pull state
		let mut pull_state = MvtPullingState::build_from_store_file().await?;
```

which makes it so the 10 transfers after the pull state `start_version` are picked up:

```
async fn get_account_events(
	rest_url: &str,
	account_address: &str,
	event_type: &str,
	field_name: &str,
	start_version: u64,
) -> Result<Vec<VersionedEvent>, BridgeContractError> {
	let url = format!(
		"{}/v1/accounts/{}/events/{}/{}",
		rest_url, account_address, event_type, field_name
	);

	//	tracing::info!("ICI url: {:?}", url);
	let client = reqwest::Client::new();

	// Send the GET request

	let response = client
		.get(&url)
		.query(&[("start", &start_version.to_string()[..]), ("limit", "10")])
		.send()
		.await
		.map_err(|e| {
			BridgeContractError::OnChainError(format!(
				"MVT get_account_events get request error:{}",
				e
			))
		})?;
```

So old events would just be ignored, and old transfers would never get processed. This would result in poor user experiences, especially given that Bardock has tended to generate occasional 502 errors. 

Make it so the relayer: 

1. looks for older pending events, 
2. finds whether any transfers need to be processed further based on those events, and then 
3. processes the transfers as appropriate.

Related is this improvement to the front-end UI, so users can see a list of their pending transfers: https://github.com/movementlabsxyz/bridge-interface/issues/6

**Comment by musitdev** [comment]
From the screenshot, the issue came from missed Eth events. The code corresponds to Movement monitoring, so it's not related to the issue.
The Eth event monitoring misses some initiated events. It can come from the connection, but as be do pulling, it means that we miss some block or don't listen to the right contract.
Can you put the Tx that initiated the transfer to see the contract address?

**Comment by musitdev** [comment]
By bad I made a mistake. The transfer is locked. So the bridge doesn't detect the counterpart complete on Mvt chain.
Effectively it means that the relayer misses an event.
Is it possible to re-sent the complete transfer to see if the relayer detects it?
If an error occurs on the event pulling the version shouldn't change until the pulling succeeds.
I'll look at the code to see if this logic is ok.

**Comment by andygolay** [comment]
> From the screenshot, the issue came from missed Eth events. The code corresponds to Movement monitoring, so it's not related to the issue. The Eth event monitoring misses some initiated events. It can come from the connection, but as be do pulling, it means that we miss some block or don't listen to the right contract. Can you put the Tx that initiated the transfer to see the contract address?

Would the log `"Chain two event stream return an error:Error during onchain call:MVT get_account_events status error 502 Bad gateway"` correspond to missed events on the Movement side?

I think I was incorrect about whether lock was called. It seems the transfer state is Locked must mean the lock function was called, according to the code. I just didn't see the transactions on Bardock. Bardock explorer or the chain were down, for about 5 hours, or maybe there were no transactions.

<img width="1624" alt="image" src="https://github.com/user-attachments/assets/55d40f72-716f-4a64-93de-8c6a21e9e670">

Here are the transactions for the initiator address: https://holesky.etherscan.io/address/0xccc20f4f411c3d5562b99cfdf876394096ea9345

On the Movement side when I run `curl "https://testnet.bardock.movementnetwork.xyz/v1/accounts/0xb118a531aa5efb194f5e322aeee8e9d1e98c6220936d1cee90e1480911d51d64/transactions?start=0&limit=30" | jq -r '.[].hash'` I only get these transactions:

```
0x483f8b6ea08b1bdd12d17a6368e3b3a02e266397f49d0d2b5f48272c2e9a4dc0
0xd3d7f1884b00edfdf3dbfab9c2616b6b625f4deeae17046ac816f9d8732b1b3f
0x366d7614b16ff6abcd8be9dd2b392b644168df44c13b4a5ace56b92f46c16751
0x263fd20f52e1788fc4598c281ae88d1ec875d14a0213b46a6a04f5a82653234f
0x03e571159cdd60a3863768bccf1289b92de93dd1f5afcadc1b8839ead8f136b0
0x2b337da76c4a2a74c3585c2f94b12f130fe1992c3ce4b0259492f37dbb7d9d02
0x529e6a081b1126e38fe0de9fd372a4925cdd43c6c1bea47b9e811f840785aaea
```

none of which is a `lock_bridge_transfer` call.

Front-end with the above two addresses connected:
<img width="997" alt="image" src="https://github.com/user-attachments/assets/ee526d06-2757-421d-a305-f93fa2d8204a">


I just tried a few transfers and they aren't being added to the logs. The logs in there must have been old. And there aren't any `lock_bridge_transfer` calls showing in Bardock explorer. So yes I think you're right, the relayer isn't picking up the Eth-side event for some reason.

**Comment by andygolay** [comment]
We restarted the bridge and now transfers are working. It seems like the Eth-side event listening may have fallen asleep or stopped processing events properly. Therefore, #782 may be a fix for this.
