### ISSUE TITLE
Rename suzuka-full-node

### ISSUE THREAD

**Issue by rolandoesparza** [movementlabsxyz/movement#848]
Background:
We want to remove reference to "suzuka" on suzuka-full-node as we have testnets with different names and infra partners are getting confused when deploying on Bardock testnet.

Options:
1) Rename suzuka-full-node to testnet-full-node
2) Rename suzuka-full-node to full-node
2) Make a copy of suzuka-full-node and rename to bardock-full-node

Priority: Urgent (P0)

**Comment by bhenhsi** [comment]
Option to consider: movement-full-node or mvmt-full-node
