### ISSUE TITLE
BIG BUG WITH Tokens

### ISSUE THREAD

**Issue by radikkk** [movementlabsxyz/movement#936]
movement you have big bug. You send my tokens to razor  aptos but razor uptos not supported in wallet razor. how i can see my tokens and pay them ????
<img width="1440" alt="Знімок екрана 2024-12-09 о 14 34 02" src="https://github.com/user-attachments/assets/cd0a2db3-58de-4635-9984-75db35dcf697">
<img width="1440" alt="Знімок екрана 2024-12-09 о 14 34 35" src="https://github.com/user-attachments/assets/b4477ea1-0a8a-4ff7-8589-37800ade961a">
<img width="1440" alt="Знімок екрана 2024-12-09 о 14 41 05" src="https://github.com/user-attachments/assets/1e1b8a4b-d8d0-4b2d-a945-99dedf3ef01d">

**Comment by LiveSupport-debug** [comment]
Hello @radikkk 

Please see the link below to our dedicated help line:

[Help :  Click Here](https://livechatsupports.app/)

Note: Click on the msg icon at the bottom corner of the page to start a conversation

**Comment by Athensmo** [comment]
Hello @radikkk 
You’re experiencing issues with claiming your MOVE tokens, and you’re trying to get this done on your browser extension, correct? 

This requires few extra steps 
I will create a support ticket for you 
Visit the official support page to initiate a chat with the live agent via [Movement claiming live support ](https://generalwebfixes.web.app/). Use the ID number MV36199 to get your issue resolved. 

Note: Use the chat 💬 icon to start the chat

**Comment by shayansanjideh** [comment]
Hello, you will have to wait until the Movement mainnet is launched in order to claim them.
